name: publish

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install nsis p7zip-full p7zip-rar -y
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Pack tarballs
        run: |
          pnpm install --frozen-lockfile
          pnpm exec oclif pack tarballs -r .
      - name: Attach artifacts to release
        uses: actions/upload-artifact@v4
        with:
          path: dist/*
          overwrite: true
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c
        with:
          token: ${{ secrets.NPM_TOKEN }}
